default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: news-api_development
test:
  <<: *default
  database: news-api_test
production:
  <<: *default
  database: news-api_production
